name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install
      run: sudo apt-get install cmake qt5-default qtbase5-dev liblcms2-dev
    - name: build
      run: |
        mkdir build && cd build
        cmake ..
        make
